package com.example.carvix.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class Strings(
    val appName: String,
    val mechanic: String,
    val headMechanic: String,
    val admin: String,
    val home: String,
    val messages: String,
    val profile: String,
    val zayavki: String,
    val mechanics: String,
    val transport: String,
    val sotrudniki: String,
    val newReq: String,
    val inProgress: String,
    val waitParts: String,
    val done: String,
    val rejected: String,
    val all: String,
    val request: String,
    val description: String,
    val priority: String,
    val creator: String,
    val createdAt: String,
    val ts: String,
    val markaModel: String,
    val gosNomer: String,
    val inventNomer: String,
    val mileage: String,
    val state: String,
    val repair: String,
    val mechanicLabel: String,
    val headMechLabel: String,
    val started: String,
    val finished: String,
    val laborCost: String,
    val partsCost: String,
    val comment: String,
    val result: String,
    val takeInWork: String,
    val complete: String,
    val reject: String,
    val deleteReq: String,
    val createRequest: String,
    val tipRemonta: String,
    val saveBtn: String,
    val cancel: String,
    val confirm: String,
    val edit: String,
    val deleteBtn: String,
    val newEmployee: String,
    val fio: String,
    val login: String,
    val password: String,
    val newPassword: String,
    val role: String,
    val division: String,
    val sendMessage: String,
    val messagePlaceholder: String,
    val noMessages: String,
    val noRequests: String,
    val noEmployees: String,
    val noVehicles: String,
    val retry: String,
    val loading: String,
    val settings: String,
    val theme: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val russian: String,
    val english: String,
    val logout: String,
    val activeRepairs: String,
    val priorityCritical: String,
    val priorityHigh: String,
    val priorityMedium: String,
    val priorityLow: String,
    val priorityPlanned: String,
    val statusNew: String,
    val statusInProgress: String,
    val statusDone: String,
    val statusRejected: String,
    val statusWaitParts: String,
    val chatWith: String,
    val chooseRecipient: String,
    val noConversations: String,
    val errFillFields: String,
    val errLoadFailed: String,
    val deleteChat: String,
    val deleteChatConfirm: String
)

val RuStrings = Strings(
    appName = "Carvix",
    mechanic = "Механик",
    headMechanic = "Гл. механик",
    admin = "Админ",
    home = "Главная",
    messages = "Сообщения",
    profile = "Профиль",
    zayavki = "Заявки",
    mechanics = "Механики",
    transport = "Транспорт",
    sotrudniki = "Сотрудники",
    newReq = "Новые",
    inProgress = "В работе",
    waitParts = "Запчасти",
    done = "Выполнены",
    rejected = "Отклонённые",
    all = "Все",
    request = "Заявка",
    description = "Описание проблемы",
    priority = "Приоритет",
    creator = "Создатель",
    createdAt = "Дата создания",
    ts = "Транспортное средство",
    markaModel = "Марка/Модель",
    gosNomer = "Гос. номер",
    inventNomer = "Инв. номер",
    mileage = "Пробег",
    state = "Состояние",
    repair = "Ремонт",
    mechanicLabel = "Механик",
    headMechLabel = "Гл. механик",
    started = "Начало",
    finished = "Окончание",
    laborCost = "Стоимость работ",
    partsCost = "Стоимость запчастей",
    comment = "Комментарий",
    result = "Итог",
    takeInWork = "Взять в работу",
    complete = "Завершить",
    reject = "Отклонить",
    deleteReq = "Удалить заявку",
    createRequest = "Создать заявку",
    tipRemonta = "Тип ремонта",
    saveBtn = "Сохранить",
    cancel = "Отмена",
    confirm = "Подтвердить",
    edit = "Редактировать",
    deleteBtn = "Удалить",
    newEmployee = "Новый сотрудник",
    fio = "ФИО",
    login = "Логин",
    password = "Пароль",
    newPassword = "Новый пароль (опц.)",
    role = "Роль",
    division = "Подразделение",
    sendMessage = "Отправить",
    messagePlaceholder = "Сообщение...",
    noMessages = "Сообщений нет",
    noRequests = "Заявок нет",
    noEmployees = "Сотрудников нет",
    noVehicles = "Нет ТС",
    retry = "Повторить",
    loading = "Загрузка...",
    settings = "Настройки",
    theme = "Тема",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    language = "Язык",
    russian = "Русский",
    english = "English",
    logout = "Выйти",
    activeRepairs = "В работе",
    priorityCritical = "Критический",
    priorityHigh = "Высокий",
    priorityMedium = "Средний",
    priorityLow = "Низкий",
    priorityPlanned = "Плановый",
    statusNew = "Новая",
    statusInProgress = "В работе",
    statusDone = "Выполнена",
    statusRejected = "Отклонена",
    statusWaitParts = "Ожидание запчастей",
    chatWith = "Чат с",
    chooseRecipient = "Выберите собеседника",
    noConversations = "Диалогов пока нет",
    errFillFields = "Заполните все поля",
    errLoadFailed = "Не удалось загрузить",
    deleteChat = "Удалить чат",
    deleteChatConfirm = "Удалить весь диалог? Это действие нельзя отменить."
)

val EnStrings = Strings(
    appName = "Carvix",
    mechanic = "Mechanic",
    headMechanic = "Head Mechanic",
    admin = "Admin",
    home = "Home",
    messages = "Messages",
    profile = "Profile",
    zayavki = "Requests",
    mechanics = "Mechanics",
    transport = "Vehicles",
    sotrudniki = "Employees",
    newReq = "New",
    inProgress = "In progress",
    waitParts = "Parts",
    done = "Completed",
    rejected = "Rejected",
    all = "All",
    request = "Request",
    description = "Problem description",
    priority = "Priority",
    creator = "Created by",
    createdAt = "Created at",
    ts = "Vehicle",
    markaModel = "Make/Model",
    gosNomer = "Plate number",
    inventNomer = "Inv. number",
    mileage = "Mileage",
    state = "State",
    repair = "Repair",
    mechanicLabel = "Mechanic",
    headMechLabel = "Head mechanic",
    started = "Started",
    finished = "Finished",
    laborCost = "Labor cost",
    partsCost = "Parts cost",
    comment = "Comment",
    result = "Result",
    takeInWork = "Take in work",
    complete = "Complete",
    reject = "Reject",
    deleteReq = "Delete request",
    createRequest = "Create request",
    tipRemonta = "Repair type",
    saveBtn = "Save",
    cancel = "Cancel",
    confirm = "Confirm",
    edit = "Edit",
    deleteBtn = "Delete",
    newEmployee = "New employee",
    fio = "Full name",
    login = "Login",
    password = "Password",
    newPassword = "New password (optional)",
    role = "Role",
    division = "Division",
    sendMessage = "Send",
    messagePlaceholder = "Message...",
    noMessages = "No messages",
    noRequests = "No requests",
    noEmployees = "No employees",
    noVehicles = "No vehicles",
    retry = "Retry",
    loading = "Loading...",
    settings = "Settings",
    theme = "Theme",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    russian = "Русский",
    english = "English",
    logout = "Log out",
    activeRepairs = "Active",
    priorityCritical = "Critical",
    priorityHigh = "High",
    priorityMedium = "Medium",
    priorityLow = "Low",
    priorityPlanned = "Planned",
    statusNew = "New",
    statusInProgress = "In progress",
    statusDone = "Completed",
    statusRejected = "Rejected",
    statusWaitParts = "Waiting for parts",
    chatWith = "Chat with",
    chooseRecipient = "Choose recipient",
    noConversations = "No conversations yet",
    errFillFields = "Fill all fields",
    errLoadFailed = "Loading failed",
    deleteChat = "Delete chat",
    deleteChatConfirm = "Delete the entire conversation? This cannot be undone."
)

val LocalStrings = staticCompositionLocalOf { RuStrings }
